drive:
  data_dir: 'simulations'  # all simulations are stored here
  sim_name: 'new_sim'      # the images and driving log of the current simulation are stored here
  model: 'models/dave2-dataset5-823.h5'   # the self-driving car model, as h5 file
  anomaly_detector: 'sao/VAE-ICSE20.h5'   # the anomaly detector model, as h5 file
  threshold: 0.0454  # threshold for the anomaly/outlier detection
  speed: 35    # max speed of the self-driving car (suggested maximum value is 35)
  max_laps: 2  # maximum number of laps before the simulation is stopped
quality_metrics:
  granularity: sector  # the granularity of the analysis [frame | sector]
train_sdc:
  data_dir: 'datasets/dataset5'  # the folder containing the training data as retrieved by the Udacity simulator
  test_size: 0.2  # test size fraction
  keep_prob: 0.5  # dropout probability
  samples_per_epoch: 100  # number of samples of the training set considered at each epoch
  batch_size: 128  # how many images are fed at the same time to the GPU
  save_best_only: 'true'
  learning_rate: 1.0e-4