name: udacity-self-driving-car
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy=1.16.0
  - pandas
  - tensorflow=1.14.0
  - keras=2.2.4
  - scikit-learn
  - opencv
  - pillow
  - eventlet
  - flask
  - python-socketio